import = ["~/.config/alacritty/rosepine.toml"]
# import = ["~/.config/alacritty/tokyonight.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 20

[font.bold]
style = "Regular"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
#family = "FiraCode Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
title = "alacritty"
decorations = "buttonless"
# opacity = 1
opacity = 0.90
blur = true
startup_mode = "Windowed"

[window.padding]
x = 12
y = 12

[window.dimensions]
columns = 120
lines = 35

[window.position]
x = 200
y = 100
